### ISSUE TITLE
Add YAML ending to template

### ISSUE THREAD

**Issue by hellquist** [kaiiiz/obsidian-raindrop-highlights-plugin#10]
Hi! Thanks for a great plug! Very useful indeed.

More of a feature request (optional or not from the user-perspective):

I would have loved if the YAML block ending (the last "---", after the "raindrop_last_update:" line) was part of the template that I could influence. If it were at the top of the template that I can edit in the modal I could add my own datafields to the YAML block. Currently I don't see a way to do that...or am I missing something somewhere else?

**Comment by kaiiiz** [comment]
> Currently I don't see a way to do that...or am I missing something somewhere else?

This feature is not currently supported by this plugin.

> I would have loved if the YAML block ending (the last "---", after the "raindrop_last_update:" line) was part of the template that I could influence. If it were at the top of the template that I can edit in the modal I could add my own datafields to the YAML block.

It's dangerous to include the frontmatter in the content template in my opinion, since this may easily corrupt the YAML parsing function if the user doesn't set it up properly.

It's better to add another template dedicated to the frontmatter rendering. If the template is not parsed correctly by the YAML parsing function or the required fields don't exist in the template, it'll reject the update.

**Comment by hellquist** [comment]
> It's dangerous to include the frontmatter in the content template in my opinion, since this may easily corrupt the YAML parsing function if the user doesn't set it up properly.

Understood. I guess I, as an fairly advanced user, fail to see all the ways someone else could mess this up. I already run a complete set of templates (via Templater plug-in) for all my notes and note-types, with a highly specialised YAML block in each of those templates. The benefits of that is that all the tags, UID and a bunch of date-specific tags, which are auto-generated, all gets linked up automatically in my entire ”system”, including the graph, in a way that Dataview (the plugin) tags (with ”::”) just can’t do, and that in turn enables me to get a clear view of ”_what_” was created ”_where_” and ”_when_”, all via YAML, and without ”cluttering up” the actual content.

> It's better to add another template dedicated to the frontmatter rendering. If the template is not parsed correctly by the YAML parsing function or the required fields don't exist in the template, the plugin will reject the update.

Cool, I will have to explore this further, and to see if there is a way for me to ”intercept” the creation by the plugin.

Just a reminder that my suggestion both had a possible ”optional” part (for the end-user, perhaps as a checkbox or similar) as well as **not** touching the `raindrop_created` or `raindrop_last_update` YAML variables, in a (in my mind) perhaps an ”advanced mode” where the `——` would be part of the template (in ”advanced” mode) or as it is today (in a not-advanced-mode).

Anyways, just a thought. I shall have a look at if I can add another template and intercept the plug-in, ideally in an update-persistent way.

PS. Typing this on my iPad which seem to have opinions on how to handle 3 consecutive ”-” in a web form, so might render weirdly in this reply. The intention is to type the 3 YAML block ending hyphens in any case. :)

**Comment by akosbalasko** [comment]
Oh, I think I had the same feat. request here: https://github.com/kaiiiz/obsidian-raindrop-highlights-plugin/issues/15 sorry for the duplication.

**Comment by kaiiiz** [comment]
The basic support for the front matter template feature has been implemented in the latest release (v0.0.14). If you find any bugs, feel free to open another issue. Thanks.
