### ISSUE TITLE
Add ability to only sync bookmarks with notes, not all bookmarks regardless of if they have notes or not.

### ISSUE THREAD

**Issue by tekwizz123** [kaiiiz/obsidian-raindrop-highlights-plugin#11]
Currently the app doesn't scale very well when dealing with a mix of bookmarks that have highlights and those that do not. For instance if you have 400 bookmarks that contain 50 bookmarks with highlights, and 350 without, instead of providing an option to just download those 50 bookmarks with highlights, you'll instead get 400 bookmarks each downloaded into their own separate folder.

What makes this worse is that there is no tag or similar to differentiate these files, so you get a big jumbled mess of notes that you now need to sort though in order to figure out which entries had notes, and which ones do not.

Ideally we should have the option to not download entries that don't contain highlights however if this is not possible then it would be quite helpful to have an option to make the plugin filter out those bookmarks that don't have highlights associated with them and only save the ones that do have highlights into their own files.

**Comment by kaiiiz** [comment]
It's possible to filter out bookmarks without highlights after the plugin receives the API response. Thanks for the suggestion.

**Comment by kaiiiz** [comment]
This feature has been implemented in the latest release (v0.0.13).
