### ISSUE TITLE
Highlights template does not accept changes

### ISSUE THREAD

**Issue by wjfeeney** [kaiiiz/obsidian-raindrop-highlights-plugin#12]
The Highlights template does not accept my changes. I changed the "set callout =" to be "note" (red), "important" (green). However, the default remains: "danger" (red), and "check" (green). What do I need to do to get my callout types?

**Comment by kaiiiz** [comment]
Please provide your full template content to let me better understand the problem. Thanks.

**Comment by wjfeeney** [comment]
I apologize. The changes were made after I relaunched Obsidian and re-synced.

**Comment by wjfeeney** [comment]
I apologize. After I closed and opened Obsidian, and resynced, all the new callout types I set in the template work as expected. I  do have another issue regarding header colors; I'll open a new issue for it. Again, I apologize for the false alarm.
