### ISSUE TITLE
Cannot pull highlights from Unsorted folder

### ISSUE THREAD

**Issue by Tanzeel159** [kaiiiz/obsidian-raindrop-highlights-plugin#13]
Right now if we need to pull highlights from Raindrop we need to add collection folder and Raindrop pulls the highlights.
But there are many bookmarks in Unsorted folder with highlights.
It would be good to add unsorted as collections folder so that we can import those highlights too.
Great job with the plugin btw

**Comment by kaiiiz** [comment]
Thanks for reporting the bug. This should be fixed in the new release (v0.0.13).
