### ISSUE TITLE
can callout headers be the same color as the highlight color?

### ISSUE THREAD

**Issue by wjfeeney** [kaiiiz/obsidian-raindrop-highlights-plugin#14]
Can the callout headers be the same color as the highlight color? As it is with the provided template, (1) red highlights are contained in a callout with a blue header; (2) blue highlights in a callout with a teal color; (3) yellow highlights in a callout with a grey header. Green highlights are okay--in a callout with a green header.

**Comment by kaiiiz** [comment]
The color of the callout block depends on the color of the theme. This plugin only gives a relatively simple example to customize the rendered content using the Nunjucks template.

The default template is tested under the default Obsidian theme. If you use another community theme, you should modify the template accordingly.

**Comment by robertandrews** [comment]
You can use [named Obsidian call-out types](https://help.obsidian.md/How+to/Use+callouts)...

![IMG_0493](https://user-images.githubusercontent.com/3158787/195973064-375aac0c-44b3-481f-a29e-efc5ad89c19b.jpeg)

Eg.:

```
> [!SUCCESS]
> Lorem ipsum dolor sit amet
```

They wouldn't necessarily carry the correct _semantic_ meaning... In every case, that might arguably be...

> [!QUOTE]
> Lorem ipsum dolor sit amet
```

... since they are "quotes" from a web page.

But it would set a colour, one which could match the highlight colours.

As said, however, colours are set at theme level, so are still subject to variation.

**Comment by kaiiiz** [comment]
Close due to inactive.
