### ISSUE TITLE
Feat. request: include frontmatter to the template

### ISSUE THREAD

**Issue by akosbalasko** [kaiiiz/obsidian-raindrop-highlights-plugin#15]
Hi @kaiiiz ! 

First of all: it's a game-changer plugin for me! Congrats!

The only one missing point for me and for my workflow is to allow to add tags into the frontmatter of the md files generated, because that section is observed by the Tags plugin which means that the tags added in Raindrop could be recognized by Obsidian instantly. Could you please consider the implementation of this feature request? I would be really grateful for it. 

I see that raindrop_id is meaningful and required due to the proper behaviour, and, as I read the code it is must to place these metainfo in to Frontmatter. So one possible solution came to my mind, what if the frontmatter won't be separated statically as how currently it is implemented, but allowing the template to begin with a continued frontmatter section, end it, and then start the real content? This different behaviour can be controlled by a toggle in the settings. 
If you don't mind, but you don't have time to implement it, I'd happily implement this feature in a PR.     

Thank you very much!

**Comment by kaiiiz** [comment]
Close as duplicate
