### ISSUE TITLE
Yaml Frontmatter processing is not consitent

### ISSUE THREAD

**Issue by dredhorse** [kaiiiz/obsidian-raindrop-highlights-plugin#21]
I have the following Frontmatter:

```
UUID: <% tp.date.now("YYYYMMDDHHmmss") %>
DateStamp: <% tp.date.now("YYYY-MM-DD") %>
Updated: 
publish: false
language: de
Vault: Privat
Year: <% tp.date.now("YYYY") %>
title: "SM - {{title}}" 
ResourceNote: 
```

while there is an issue with Templater running at too many notes at the same time I would like to point your attention to the title line.

I declare it as 

`
title: "SM - {{title}}"
 `

The result can be:

- no "
- only a " at the beginning
- " at the beginning and the end

This happens if I do 8 "bookmarks" at the same time.

It could be an issue due to templater, haven't checked the yaml without templater.

**Comment by dredhorse** [comment]
here is a note which I have issues with, as you can see in line 13 - 14 additional spaces are added to the title. https://gist.github.com/dredhorse/5ed5c14e581ffadc5a2337ed13f3b4ae
Config can be found here: https://gist.github.com/dredhorse/90df46ac432786ff0ff7c955ce96b265
As you can see I try to wrap the yaml title and alias in ' but this isn't done.
On this note it is done though.. might it be the escaping in general of the : ? https://gist.github.com/dredhorse/5ce21aae97e9a9db06381dae08313252

**Comment by kaiiiz** [comment]
I've checked this case in 0.0.15, and it seems fixed.
