### ISSUE TITLE
How to get rid of null after a : ?

### ISSUE THREAD

**Issue by dredhorse** [kaiiiz/obsidian-raindrop-highlights-plugin#22]
I have 
Updated: 
in my Frontmatter

the result is:
Updated: null

Any idea on how to get rid around this?

**Comment by kaiiiz** [comment]
The frontmatter template is currently implemented by converting the YAML object to the frontmatter. `null` means that this field is `null` in the YAML object. This can be enhanced by changing the frontmatter rendering code.

**Comment by kaiiiz** [comment]
Implemented in 0.0.15
