### ISSUE TITLE
How to remove a newline if the if-statement if false?

### ISSUE THREAD

**Issue by dredhorse** [kaiiiz/obsidian-raindrop-highlights-plugin#23]
I'm using an adaption of the original template
```
{% if tags|length -%}> - Document Tags:: #Raindrop/{{ tags | join(", #Raindrop/") }}{% endif %}
{% if excerpt -%}> - Summary:: {{excerpt}}{% endif %}
{% if link -%}> - Source URL:: {{link}}{% endif %}
```
which creates the following if excerpt is empty
```
> - Document Tags:: #Raindrop/tag

> - Source URL:: https:/........
```
I tried several different options of placing the - before or after the % but either I have this empty line or I don't have any newline or the  first line even removing the newline of the previous line.

Any idea?

**Comment by kaiiiz** [comment]
How about the following template?

```
{%- if excerpt -%}> - Summary:: {{excerpt}}{%- endif -%}
```

**Comment by kaiiiz** [comment]
How about:

```
{% if tags|length -%}> - Document Tags:: #Raindrop/{{ tags | join(", #Raindrop/") }}{% endif %}
{%- if excerpt -%}> - Summary:: {{excerpt}}{%- endif %}
{% if link -%}> - Source URL:: {{link}}{% endif %}
```

`{%-` strips the whitespace right before the tag, but `%}` keeps the line feed in the second line.

**Comment by kaiiiz** [comment]
Closed due to inactive.
