### ISSUE TITLE
Collection and Link/Page Title

### ISSUE THREAD

**Issue by renna999** [kaiiiz/obsidian-raindrop-highlights-plugin#27]
Hi,

how can I make sure I get the collection title in the Frontmatter - {{title}} is used for both the title of the page and the collection name - how do I differntiate those?

Thanks,
Daniel

**Comment by kaiiiz** [comment]
Please use `{{collection.title}}`. The document should be enhanced for more details about this.

**Comment by kaiiiz** [comment]
Fix in 0.0.15
