### ISSUE TITLE
Feature Request: Sanitise file name to remove disallowed characters in filenames

### ISSUE THREAD

**Issue by tekiegirl** [kaiiiz/obsidian-raindrop-highlights-plugin#31]
Hi,

Thank you for this plugin, I find it incredibly useful!
I noticed recently that my mobile version of Obsidian kept crashing on load when indexing the vault and it turns out it is due to there being files with disallowed characters (such as % : ;) and I have tracked these down to Raindrop bookmark titles.

Would it be possible to add in removal/replacement of disallowed characters? Possibly with the option of specifying a replacement character (e.g. - or _).

Many thanks :)

**Comment by kaiiiz** [comment]
Implemented in 0.0.17. This request can be fulfilled using `replace` function in the template.

**Comment by dylan-k** [comment]
What is the replace function that would sanitize the filename to be allowed for both mac and windows?
