### ISSUE TITLE
Autosync error

### ISSUE THREAD

**Issue by mickallen** [kaiiiz/obsidian-raindrop-highlights-plugin#34]
The auto sync functionality does nor work for me I get the following error in the console
![image](https://user-images.githubusercontent.com/14942727/212338617-5761c1e4-fd6a-4959-80e5-e56b060f3ccf.png)

**Comment by kaiiiz** [comment]
I've tested this feature several times without any issues. The error message gives only a little information, but I guess this error is caused by network problems.

Interestingly, I found another bug when checking the auto sync functionality. I've opened a separate issue for that #38.

**Comment by kaiiiz** [comment]
Closed due to inactive.
