### ISSUE TITLE
Feature Request: Identify if link to media and allow customizing template based on result

### ISSUE THREAD

**Issue by jpfieber** [kaiiiz/obsidian-raindrop-highlights-plugin#35]
Raindrop.io allows for saving an image (right-click on image and choose Save Image).  I'd love to be able to customize the template to do something like `{% if link.image %} ![image]({{link}}){% endif %}` to have a link to the image embedded in the note, and have the image appear in the note, but only have this happen if the link is to an image (or other media possibly).

**Comment by kaiiiz** [comment]
You can use `type` property to check whether the bookmark is a `link` or an `image`.
