### ISSUE TITLE
An article or collection deleted in obsidian is never synced again

### ISSUE THREAD

**Issue by oliviercarizzoni** [kaiiiz/obsidian-raindrop-highlights-plugin#39]
After selecting a collection, it is well synced the first time, however if we delete an article or a collection in obsidian, the plugin will not sync it anymore.

I tried to change the append mode settings, or alter the data.json in the plugin folder, nothing works. Only i have found reinstalling the plugin for a fresh restart.

This makes testing templates quite annoying. Thanks for this great plugin anyway.

Regards, Olivier

**Comment by kaiiiz** [comment]
The plugin stores the last sync time after every sync and only syncs the new update to reduce unnecessary requests. Please try "Reset sync" in the plugin setting page to reset the last sync time, and the full resync should be triggered in the next sync.

**Comment by oliviercarizzoni** [comment]
Oh thanks I didn't see that option down below !
