### ISSUE TITLE
Please update documentation with reference of file which stores the API Token

### ISSUE THREAD

**Issue by dredhorse** [kaiiiz/obsidian-raindrop-highlights-plugin#4]
Hi,
thanks for making it clear that you store the token (a lot of the other devs don't do that).

But could you add a reference to the file in which it is stored?

I guess you do store it in plaintext (which is fine) but this should also be mentioned.

To many people are sharing their vault and their .obsidian directory 😀

**Comment by kaiiiz** [comment]
As the document mentioned, it's stored in the browser's localStorage. This is not stored in any file that can be synced across devices.

> To many people are sharing their vault and their .obsidian directory 😀

Yes, this caused a serious security risk. To the best of my knowledge, storing the token in the localStorage is the best trade-off between security and convenience, unless obsidian provides a more advanced API for storing sensitive information.

**Comment by dredhorse** [comment]
uups.. now I see it, so I need to add the api token to every device. 
Cumbersome but better then to store the api in a plain text file, I agree.
Didn't read through the code enough to see if there is a message poping up if the token is not there.

**Comment by kaiiiz** [comment]
> Didn't read through the code enough to see if there is a message poping up if the token is not there.

https://github.com/kaiiiz/obsidian-raindrop-highlights-plugin/blob/bf3dd334a2b8cb1d1ac848bdfe6c755e867c98ae/src/api.ts#L18-L21

Token checking logic is at the beginning of the API request, and the error will be resolved in the `syncCollection` function.

https://github.com/kaiiiz/obsidian-raindrop-highlights-plugin/blob/bf3dd334a2b8cb1d1ac848bdfe6c755e867c98ae/src/sync.ts#L33-L49

I'm considering moving the checking logic inside the `get` function of `tokenManager`.

**Comment by dredhorse** [comment]
ah, thanks for this information
