### ISSUE TITLE
Add feature to use command palet to sync a collection

### ISSUE THREAD

**Issue by mathisgauthey** [kaiiiz/obsidian-raindrop-highlights-plugin#40]
Hi there. I think it would be a good addition to be able to select a new collection to sync directly from obsidian using the command palet instead of having to go back to the plugin settings.

I'm creating a new collection fro each subject or project I'm working on, hence I would need that kind of faster workflow process.

Thanks in advance ! And thanks for the work, it's exaclty what I was missing !

**Comment by kaiiiz** [comment]
Can you provide more details of your requests? Is a shortcut of the "Manage" button in the plugin settings fulfilled your need? Thanks.

**Comment by kaiiiz** [comment]
Implemented in 0.0.18.
