### ISSUE TITLE
How to remove Emoji in the title?

### ISSUE THREAD

**Issue by zhongjis** [kaiiiz/obsidian-raindrop-highlights-plugin#41]
Hi there!

First off, I want to say how fantastic this plugin is! It has truly improved my workflow and was the primary reason for me switching to Obsidian. Thank you so much for your hard work! 😄

I have a question regarding the customized `{{title}}`. I'm not very familiar with Nunjucks, and I'm curious to know if there's a way for the plugin to remove emojis from the title. 

I've encountered some issues when syncing my files with **Box.com**. The files with emojis in their titles (e.g. `Example title 😄`) are causing some trouble during the sync process and are being marked as `problem files` on MacOS...

Any help is appreciated XD

**Comment by scottwalter-nice** [comment]
Try this:

```
{{ title | replace(r/[^ -\u2122]+ +| *[^ -\u2122]+/,"")}}
```

**Comment by zhongjis** [comment]
> Try this:
> 
> ```
> {{ title | replace(r/[^ -\u2122]+ +| *[^ -\u2122]+/,"")}}
> ```

It worked! Thank you so much XD

**Comment by zhongjis** [comment]
See above
