### ISSUE TITLE
List of all collection don't show

### ISSUE THREAD

**Issue by spatialy** [kaiiiz/obsidian-raindrop-highlights-plugin#44]
Hi how can I scroll to see all the collections and select the one below?

![Screenshot 2023-05-06 at 4 51 50 PM](https://user-images.githubusercontent.com/5605867/236646275-66c0da60-0718-4f34-ae61-d9c8994e0160.png)

**Comment by kaiiiz** [comment]
Hi, I'm able to scroll the collection list. Please check your theme, custom CSS, and plugin setting.

<img width="1245" alt="image" src="https://github.com/kaiiiz/obsidian-raindrop-highlights-plugin/assets/30596812/b8313c7f-999c-407e-a4ee-853d1932b56b">

**Comment by kaiiiz** [comment]
Closed due to inactive.
