### ISSUE TITLE
[FR] Adds a date library to use

### ISSUE THREAD

**Issue by AtlcatlQ** [kaiiiz/obsidian-raindrop-highlights-plugin#45]
I would like to use the today's date in the title of the created files. So I think it would be useful to have a `date` function/variable/library to use: Like importing the moment.js library that Obsidian already use.

I don't know if I'm explaining my self right, but I meant something like [templater](https://silentvoid13.github.io/Templater/internal-functions/internal-modules/date-module.html)

**Comment by kaiiiz** [comment]
Implemented in 0.0.18.
