### ISSUE TITLE
Suggestion: Using a defined file to the themplates instead of a text field

### ISSUE THREAD

**Issue by AtlcatlQ** [kaiiiz/obsidian-raindrop-highlights-plugin#46]
I would to put just the path to the template to be able to modify it easier than first getting sure to all is working properly and then pasting to the text field in the options

**Comment by kaiiiz** [comment]
I'm currently not planning to implement this feature since it makes the template validation harder and will potentially reduce the stability. Also, since the template is not updated too often for most of the use cases, trading a little convenience for stability is a reasonable design choice IMO.

**Comment by AtlcatlQ** [comment]
I hadn't considered the template validation part and the stability. Now I understand and agree with that design decision.
