### ISSUE TITLE
Inlcude Bookmark Notes 

### ISSUE THREAD

**Issue by mthave** [kaiiiz/obsidian-raindrop-highlights-plugin#48]
Please include a tag for Bookmark notes in the content template. textarea name="note", that recently go support for markdown 😀.

**Comment by kaiiiz** [comment]
I do not understand your request. Can you provide more details about this improvement?

Thanks.

**Comment by mthave** [comment]
Sure, next to the note connected to a highlight there is a note section on bookmark level, https://help.raindrop.io/bookmarks/#notes/
It would be great if we could sync this to Obsidian too. I hope this helps.

**Comment by kaiiiz** [comment]
Implemented in 0.0.18.
