### ISSUE TITLE
Collections nested with more than 2 levels don't synchronize correctly

### ISSUE THREAD

**Issue by heinzochsner** [kaiiiz/obsidian-raindrop-highlights-plugin#49]
On of my raindrop collections looks like this:

![image](https://github.com/kaiiiz/obsidian-raindrop-highlights-plugin/assets/53118281/0f85eb82-92b7-4d09-a99b-2d2dea112814)

In the "Manage Collections" window, this looks like:

![image](https://github.com/kaiiiz/obsidian-raindrop-highlights-plugin/assets/53118281/76967163-7357-40ee-920e-d381ba24ea7b)

This behaviour is independent of whether the collections contain elements or not. When syncing, the folders created in Obsidian have the same wrong structure.

Thanks
Heinz ...

**Comment by kaiiiz** [comment]
Fixed in 0.0.18.

**Comment by heinzochsner** [comment]
Great, thanks!
Heinz...

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
