### ISSUE TITLE
FR: Allow Syncing of "Bookmarks"

### ISSUE THREAD

**Issue by dredhorse** [kaiiiz/obsidian-raindrop-highlights-plugin#5]
Would it be possible to sync all "Bookmarks" including Title, Description and tags based on collection and / or tags?

Everybody is always keen on the highlights, but I'm also looking for an easy way to have some bookmarks in obsidian, with Description and Tags

At the moment my process is:

1. Mark a webpage with the raindrop.io plugin, look at the automatic description and make changes if necessary, add tags and collection
2. Later on during my "triaging" in raindrop.io I take a look if the "bookmark" is still valid and needs either be processed = highlighted or bookmarked (mainly due to the fact that I would probably need to highlight everything or dive deeper into the article and take additional note).
3. If it is a bookmark I cope the URL and paste that into a "bookmark" note in obsidian, copy the description from raindrop.io and tags and add some more minor comments if necessary.
4. After processing the "bookmark" in raindrop.io I set a tag that I'm done with it.
5. Later during my "triaging" in Obsidian I then come back to that bookmark and process it further.
6. After processing the "bookmark" I tag it as done.

Being change the process to the following would streamline it a lot:

1. Mark a webpage with the raindrop.io plugin, look at the automatic description and make changes if necessary, add tags and collection to sync to obsidian
2. Later during my "triaging" in Obsidian I then come back to that bookmark and process it further.
3. After processing the "bookmark" I tag it as done in Obsidian and Raindrop.io

**Comment by kaiiiz** [comment]
I'm not quite sure what problem you have and what problem this plugin can not solve.

> Would it be possible to sync all "Bookmarks" including Title, Description and tags based on collection and / or tags?

Sync bookmarks based on collection is the current behavior. It can be configured in the "Manage Collection" settings.

To sync Title, Description, and tags for each bookmark, try to modify the template settings. The corresponding template variables are listed below:

- Title: `{{title}}`
- Description: `{{excerpt}}`
- tags: `{{tags}}`

**Comment by dredhorse** [comment]
Ah, the description of the plugin doesn't state that it does also sync bookmarks without highlights (I'm burned by Readwise not syncing notes from hypothes.is only highlights.)

**Comment by kaiiiz** [comment]
This plugin sync "all" bookmarks, including bookmarks with and without highlights.

I still do not understand your request. Do you treat this feature as an unexpected behavior?
