### ISSUE TITLE
Please tell me how to remove the parent category when getting the value from the variable {{collection.title}}?

### ISSUE THREAD

**Issue by EpolPers** [kaiiiz/obsidian-raindrop-highlights-plugin#52]
When I get the value from the variable {{collection.title}}, because the category with the note is nested, then I get the value of the parent and nested category, but I only need the value of the nested category.

**Comment by kaiiiz** [comment]
How about `{{ collection.title.split("/") | last }}`?

**Comment by kaiiiz** [comment]
Closed due to inactivity.
