### ISSUE TITLE
Raindrop isn't syncing?

### ISSUE THREAD

**Issue by flowingblaze** [kaiiiz/obsidian-raindrop-highlights-plugin#53]
Hello, 
I installed this plugin and I set it up to have my notes sync in the "raindrop" folder I made on my obsidian. I put the API key into the plugin settings as instructed. For some reason despite setting it for every 60 minutes my raindrop isn't syncing. I am on a windows computer.

**Comment by kaiiiz** [comment]
Have you selected which collections to sync? Please click the "Manage" button in the settings page to verify.

**Comment by flowingblaze** [comment]
for some reason I didn't see the manage button at all until you told me about it, thank you for your time!!! Raindrop's syncing now.
