### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by flowingblaze** [kaiiiz/obsidian-raindrop-highlights-plugin#58]
When attempting to sync my highlights I get an "Error 459" and nothing is added to my vault.

**Comment by kaiiiz** [comment]
Is this still happening? Can you provide the error log in the develop console? Thanks

**Comment by flowingblaze** [comment]
![image](https://github.com/kaiiiz/obsidian-raindrop-highlights-plugin/assets/107226733/c03026e6-32ae-428f-8c83-d55b3620a18a)
here's a picture of the errorlog since i couldn't figure out how to copy and paste from the console in obsidian.

**Comment by kaiiiz** [comment]
Duplicated. See #63. This should be fixed in v0.0.19.
