### ISSUE TITLE
Suddenly LF/CRLF issues

### ISSUE THREAD

**Issue by jimpfaff** [kaiiiz/obsidian-raindrop-highlights-plugin#59]
I use Obsidian Github to sync my Obsidian files. As of today, I am suddenly receiving LF/CRLF sync issues just with the files synced with the Raindrop plugin. I haven't had time to troubleshoot. I'll do that later. But I have made zero changes to the plugin. Just an FYI

**Comment by kaiiiz** [comment]
Hmmm... Is this still happening? I haven't encountered this problem before.

**Comment by kaiiiz** [comment]
Closed due to inactivity.
