### ISSUE TITLE
highlight URL variable - update

### ISSUE THREAD

**Issue by wjfeeney** [kaiiiz/obsidian-raindrop-highlights-plugin#60]
This is a follow-up to issue  @#51  requesting a highlightURL variable in the template to render links to open the webpage in Raindrop to view the highlight in context. You replied that it is not possible because the Raindrop API does not provide the anchor point information of the highlight.

The developer, Rustem Mussabekov, advises "to use this link **https://app.raindrop.io/my/0/item/{ID}/web** and replace {ID} with a particular bookmark id." 

I hope you will make this work.

**Comment by kaiiiz** [comment]
The `Raindrop Highlights: Open link in Raindrop` has already implemented the same thing mentioned by the developer. The actual problem is that the link corresponding to the highlight entry is not included in the api response.
