### ISSUE TITLE
(newbie question) where can i find the template file to make changes?

### ISSUE THREAD

**Issue by jhwright** [kaiiiz/obsidian-raindrop-highlights-plugin#61]
i've looked in .obsidian and poked around here in github, but not finding what i need.

what i want to accomplish is to automatically wrap all URLs from raindrop in an iframe to render linked pages and youtubes in my md files in obsidian.

thanks for your good work!

**Comment by kaiiiz** [comment]
You can edit the templates in the plugin setting page. The changes will be stored in `.obsidian/plugins/obsidian-raindrop-highlights/data.json`.

**Comment by kaiiiz** [comment]
@ruben-sg I do not understand the first question, can you provide more details? (What is "the properties"?)

"excerpt" is the summarization of the article (sometimes automatically generated by Raindrop)

<img width="476" alt="image" src="https://github.com/kaiiiz/obsidian-raindrop-highlights-plugin/assets/30596812/491ec285-c088-49b8-b6f8-d88e8edef1fe">

Contribution of FAQ is welcome!
