### ISSUE TITLE
Gracefully handle Raindrop tags containing whitespace characters

### ISSUE THREAD

**Issue by talkingwires** [kaiiiz/obsidian-raindrop-highlights-plugin#69]
Raindrop supports tags containing whitespace characters, Obsidian does not. Importing a Raindrop collection with tags containing spaces results in truncated and/or broken tags. It would be great if this plugin sanitized tags during the import process, either stripping the invalid characters, or changing them to dashes.

**Comment by kaiiiz** [comment]
You can achieve the same thing using the following template:

```
tags:
{% for tag in tags -%}- {{tag | replace(" ", "-") }}
{% endfor %}
```
