### ISSUE TITLE
Updated description and order of highlights according to the order of the article.

### ISSUE THREAD

**Issue by PentalphaE** [kaiiiz/obsidian-raindrop-highlights-plugin#7]
Congratulations. It is a great plugin.
I have two questions:
1) What can I do to make ae update a change in the item description in Raindrop, after I have synced with Obsidian.
2) Raindrop has a problem that I do not know if you can solve it with this plugin: the order of the highlights is the order of when they are made, but this can give a messy result, since it is very useful the order in which the texts appear in the article, from top to bottom.

**Comment by kaiiiz** [comment]
> What can I do to make ae update a change in the item description in Raindrop, after I have synced with Obsidian.

In the current implementation, updating the description in place is not supported since it's hard to keep track of the location of the metadata in the file, and also it's dangerous to update the whole content using the newest rendered post which may cause data loss.

I'm considering adding an option that will always keep the latest rendered result in the file, but this will lose the flexibility to add/modify the content for the synced post.

> Raindrop has a problem that I do not know if you can solve it with this plugin: the order of the highlights is the order of when they are made, but this can give a messy result, since it is very useful the order in which the texts appear in the article, from top to bottom.

No, this is nearly impossible unless Raindrop adds this information in their API.

**Comment by kaiiiz** [comment]
I've implemented the `Append Mode` option in v0.0.12. Turning this option off can keep your metadata always in the latest state, but this will lose the flexibility to add/modify the content for the synced post.

Please check it out if this option meets your requirements.

**Comment by PentalphaE** [comment]
Thank you very much for your answers.

Despite the limitations of Raindrop, you have done a great job. But I guess, in the future, future Raindrop will improve the highlights and your API.

What you point out to me will make me be more careful to edit the description at first, before syncing it via your plugin. And I will try to be neater to highlight in order.

The deactivated Append Mode can be a great solution for me, because in case of modifications I will always have the latest version of what was done in Raindrop (I don't know if it includes also the latest version of the description). And if I had something important in a previous version, I could make a copy of it in Obsidian, if I want to preserve it, before making changes in Raindrop.

For safety's sake I will use only manual synchronization.
