### ISSUE TITLE
Syncing not working

### ISSUE THREAD

**Issue by robertkodra** [kaiiiz/obsidian-raindrop-highlights-plugin#71]
Hi! I recently installed the Raindrop plugin and connected my account to it. However, syncing is not working. When I click on “Manage Collection,” it says “Loading collection” and stays like that for hours. I have a total of 400 bookmarks on my Raindrop.

I’m currently using a MacBook Pro M2. I’m not sure what could be causing this issue.

**Comment by wendingtuo** [comment]
Bump - I'm also having this issue. I can successfully connect but Manage Collections never loads, manual sync doesn't appear to do anything, and checking my last sync date briefly shows an empty pop-up bubble.

I am experiencing this on both Android and Windows 11.

**Comment by kaiiiz** [comment]
Fixed in v0.0.21.
