### ISSUE TITLE
Syncing only partially sync all the bookmarks.

### ISSUE THREAD

**Issue by KelSolaar** [kaiiiz/obsidian-raindrop-highlights-plugin#72]
Hello,

The context is special: I imported all at once a bunch of bookmarks into Raindrop that I would like to sync into Obsidian.

There is however an issue with the syncing process where it only partially syncs all the bookmarks. I have as of this writing, 351 bookmarks that I would like to import, only 194 came through at my last attempt. Originally, all my bookmarks had the same date because they were imported all at once. So I re-created them one by one every 3 seconds using the Raindrop API (with Python) but no dice.

I suspect it is an issue with the created/last update date and sorting because I commented the Raindrop API parameters for sorting and everything comes through just fine: https://github.com/kaiiiz/obsidian-raindrop-highlights-plugin/blob/main/src/api.ts#L146, https://github.com/kaiiiz/obsidian-raindrop-highlights-plugin/blob/main/src/api.ts#L158

I cannot see any related errors in the Developer console.

It is worth noting that using the Raindrop API directly (with Python) and using the `sort="-lastUpdate"` parameter pulls all the links as expected.

I tried to generate a repro file by scrambling the title and urls but this one works fine.

Cheers,

Thomas

**Comment by mathisgauthey** [comment]
Hey there @KelSolaar, I'm having the similar issue this morning.

It's weird because it worked this morning, then I reseted because I needed a drastic change in my templates and it no longer syncs all.

**Comment by kaiiiz** [comment]
It seems that Raindrop API has bug on sorting lastUpdate field with pagination. The same bookmark is returned on different page, which is unexpected. I'm thinking of implementing a full sync feature, but it would require all pages to be requested while syncing, which could be a huge performance overhead and lots of unnecessary requests.

**Comment by kaiiiz** [comment]
Fixed in v0.0.21. Sync collections from last update time is now changed to sync from created time. Two new commands `Raindrop Highlights: Sync all bookmarks (full sync)` or `Raindrop Highlights: Sync this bookmark` are introduced to perform update for existing files.
