### ISSUE TITLE
Quotation Marks are Missing in YAML Frontmatter

### ISSUE THREAD

**Issue by dylan-k** [kaiiiz/obsidian-raindrop-highlights-plugin#73]
Because titles can have colons (and so can URLs), it's helpful to wrap YAML strings in double quotes (or single quotes). This can prevent errors and warnings from YAML parsers. I tried it like this in my metadata template:

```yaml
title: "{{title}}"
```

... but the resulting content of the file doesn't include those quotation marks (double or single). It just looks like this:

```yaml
title: Titles: Sometimes They Have Colons
```

I tried it with "autoescaping" enabled and disabled, but I got the same results.
Issue seems to occur when "append mode" is enabled. 

I tried escaping the quotes with `/"` 
but this was only partially successful because it rendered it literally as 
`title: /"title: Titles: Sometimes They Have Colons/"`

It was also unsuccessful when I tried using a [raw block](https://mozilla.github.io/nunjucks/templating.html#raw).

For titles, I could just filter out any colons, but this won't work for URLs, and I also like to have URLs for the source and the raindrop.io links.

Is there any way to get the metadata template to output quotation marks?

**Comment by kaiiiz** [comment]
I've tested adding double quote to the metadata template and it work as expected. My plugin version is v0.0.20.

![image](https://github.com/kaiiiz/obsidian-raindrop-highlights-plugin/assets/30596812/ce909828-7062-41c5-ab48-2baa0703276d)

**Comment by dylan-k** [comment]
Yes, it seems to be working now.
