### ISSUE TITLE
[FR] Add support for Raindrop links in Nunjucks templates

### ISSUE THREAD

**Issue by mathisgauthey** [kaiiiz/obsidian-raindrop-highlights-plugin#75]
Hey there ! My Omnivore setup involves a linkind at the beginning of my imported saved links :

```
## Omnivore

[Read on Omnivore]({{{omnivoreUrl}}})
[Read Original]({{{originalUrl}}})
```

It would be amazing to be able to manage these as well using Nunjucks template with something like `{{raindropURL}}`.

Note : The raindrop URL is formatted this way : 
- `https://app.raindrop.io/my/COLLECTION_ID/item/ITEM_ID/preview` for a file
- `https://app.raindrop.io/my/COLLECTION_ID/item/ITEM_ID/web` for a saved link

I don't know if it would be much trouble or not, but it would certainly be useful to be able to see it inside our Raindrop webapp easily for highlighting or collection management purposes.

NB: Thanks for your plugin and reactivity, it is already really useful and this is just a proposition in case you still feel like adding new features o/ Have a good day !

**Comment by HealsCodes** [comment]
+1 

while not always needed it's a great way to get back to an existing article from Obsidian to review it or add new notes and highlights without jumping through a lot of hoops.

**Comment by kaiiiz** [comment]
Supported in v0.0.22.
