### ISSUE TITLE
The command `Raindrop Highlights: Sync this bookmark` does not work

### ISSUE THREAD

**Issue by mathisgauthey** [kaiiiz/obsidian-raindrop-highlights-plugin#77]
Hey there, since the last update, two new command appeared.

The `all sync` is working well and I use it to update my highlights, my collections changes and stuff.

But I would probably better use the `Raindrop Highlights: Sync this bookmark` command when on a note just to sync this particular note.

But when I use the command, it doesn't work and I don't get any log using `CTRL+SHIFT+I`. Any idea ?

**Comment by t3mujin** [comment]
Struggling with this one also, seems like it's not doing anything.

**Comment by kaiiiz** [comment]
Fixed in v0.0.22.
