### ISSUE TITLE
Use raindrop.io tags in Obsidian

### ISSUE THREAD

**Issue by Outlawpete285** [kaiiiz/obsidian-raindrop-highlights-plugin#8]
Hi,
just tested the plugin and I love it. I also love that it´s possible to get all tags but is it possible to format them so that they are usable and visible in the tag pane?
I tried it with renaming "Topics::" to "tags::" and adding a "#" before the tag in the template but that didn´t work. What did work was adding a "#" in front of the tag in raindrop.io, but maybe there is a better solution I´m not aware of.
Any ideas?
Best Regards

**Comment by kaiiiz** [comment]
There are many solutions due to the high customizability Nunjacks template offered.

The most simple way I know is to modify the template from:

```
{% if tags|length %}Topics:: {{ tags | join(", ") }}{% endif %}
```

to:

```
{% if tags|length %}Topics:: #{{ tags | join(", #") }}{% endif %}
```

Please refer https://mozilla.github.io/nunjucks/templating.html for more details.

**Comment by Outlawpete285** [comment]
Is it really that easy? Very cool, thanks a lot for the hint.
________________________________
Von: You-Kai Zheng ***@***.***>
Gesendet: Saturday, September 3, 2022 12:36:51 PM
An: kaiiiz/obsidian-raindrop-highlights-plugin ***@***.***>
Cc: Outlawpete285 ***@***.***>; Author ***@***.***>
Betreff: Re: [kaiiiz/obsidian-raindrop-highlights-plugin] Use raindrop.io tags in Obsidian (Issue #8)


There are many solutions due to the high customizability Nunjacks template offered.

The most simple way I know is to modify the template from:

{% if tags|length %}Topics:: {{ tags | join(", ") }}{% endif %}


to:

{% if tags|length %}Topics:: #{{ tags | join(", #") }}{% endif %}


Please refer https://mozilla.github.io/nunjucks/templating.html for more details.
