### ISSUE TITLE
Bookmarks as lists not notes

### ISSUE THREAD

**Issue by aliamini87** [kaiiiz/obsidian-raindrop-highlights-plugin#9]
Hi
Thanks a lot for this useful plugin.
I have a large number of bookmarks in my raindrop account. They have tags and I usually search them by their tags. It will be very useful if I can have these links with their tags in my obsidian vault. But not as separate notes because I don't need such number of notes. Only a list with their link and their tags in front of them is enough. 
Is it somehow possible?

**Comment by kaiiiz** [comment]
This plugin is focused on pulling the highlights from Raindrop to Obsidian notes.

I think the dataview-like feature of another [Raindrop Plugin](https://github.com/mtopping/obsidian-raindrop) meets your requirement.
